import logging

from src.ai_providers.base import BaseAIProvider

logger = logging.getLogger(__name__)


class DummyProvider(BaseAIProvider):
    """
    No-op AI provider for local development and rules engine testing.

    Always returns no alerts, so the rules engine output is the only
    signal — no API keys required, no network calls, no cost.

    Enable with: AI_PROVIDER=dummy
    """

    def __init__(self):
        logger.warning(
            "DummyProvider active — AI correlation is disabled. "
            "No alerts will be generated by the AI layer."
        )

    async def _call_api(self, prompt: str) -> str:
        return '{"is_alert": false}'
